#!/usr/bin/perl -w

use strict;

# @(#) $Id: crunch-cvsup-output,v 1.1 2004-10-14 11:07:52 matthew Exp $
#
# Very small filter that transforms the output from 'cvsup -g -L2'
# into a list of the port directories affected.  Strips out stuff
# which is part of the ports infrastructure.

MAIN:
{
    my %ports;

    while (<>) {
        chomp;
        if ( my ($p) = m@(ports/[^/]+/[^/]+)/@g ) {
            $ports{$p}++
              unless $p =~ m@/(Mk|Templates|Tools|distfiles|packages)/@;
        }
    }

    for ( sort keys %ports ) {
        print "/usr/$_\n";
    }
}
