---
abstract: 'Incremental FreeBSD ports INDEX file generation'
author:
  - 'Matthew Seaman <m.seaman@infracaninophile.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.56
configure_requires:
  ExtUtils::MakeMaker: 6.56
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FreeBSD-Portindex
no_index:
  directory:
    - inc
    - t
requires:
  BerkeleyDB: 0.25
  perl: 5.8.3
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: 2.6
