# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         FreeBSD-Portindex
version:      1.00
version_from: lib/FreeBSD/Portindex/Port.pm
installdirs:  site
requires:
    BerkeleyDB:                    0.25

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
